name: Sponsorkit
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun sponsorkit
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github-actions@users.noreply.github.com
          message: "Update sponsors [ci skip]"
          add: "sponsorkit/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
